### ISSUE TITLE
how do you use this?

### ISSUE THREAD

**Issue by vesper8** [Acidham/alfred-apple-reminder#1]
Would be great if there was an example

I would like to be able to write something like "rm pizza 10 minutes"

To have a reminder set to check my pizza in 10 minutes

Is this possible with this workflow?

Thanks

**Comment by Acidham** [comment]
My workflow is not made for natural writing in one step. I separated the steps into:
1. Enter Title
2. Enter date, you can enter `today`, `tomorrow` or even a date
3. Time
4. Enter list name or leave empty

There is another nice Reminder Workflow which supports natural writing as far as I know: https://github.com/surrealroad/alfred-reminders/releases

**Comment by vesper8** [comment]
thanks for the reply, I installed that other one and it's exactly what I was looking for. Cheers!
